[project]
name = "playwright-stealth"
version = "2.0.0"
description = "Make your playwright instance stealthy"
authors = [
    {name="AtuboDad", email="lcjasas@sina.com"},
    {name="Mattwmaster58", email="mattwmaster58@gmail.com>"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.9"

dependencies = [
    "playwright (>=1.55.0)"
]

dynamic = [ "classifiers" ]

[tool.poetry]
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]

[project.urls]
homepage = "https://github.com/Mattwmaster58/playwright_stealth"
changelog = "https://github.com/Mattwmaster58/playwright_stealth/raw/main/CHANGELOG.md"

[project.optional-dependencies]
black = ["black >= 25.9.0"]

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.2"
pytest-asyncio = "^1.2.0"

[build-system]
requires = ["poetry-core>=2.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
log_cli = true

[tool.black]
line-length = 120
